---
version: '3.7'
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  web:
    build: .
    image: youtube_watcher
    entrypoint: /docker-entrypoint.sh
    volumes:
        - .:/code
    ports:
        - "8000:8000"
    depends_on:
        - mongodb
        - broker
    environment:
      - SECRET_KEY=#5rf#)h+37^g&8kt09*336o&pa2b662%6)&yto%-0(51&r!z(k
      - DEBUG=True
      - MONGODB_NAME=mongodb
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=rootpassword
      - MONGODB_DATABASE=youtube_watcher
      - FIELD_ENCRYPTION_KEY=_-1Fw33Pl_6jSXK6NUxm02MnYjODOzrJjCFMPUuxOnY=
      - KAFKA_BOOTSTRAP_SERVERS=broker:29092
    
  consumer:
    build: .
    image: youtube_watcher
    container_name: youtube_consumer
    command: faust -A youtube_watcher.consumer:app worker -l info
    ports:
      - "6066:6066"
    depends_on:
      - mongodb
      - broker
      - web
    environment:
      - SECRET_KEY=#5rf#)h+37^g&8kt09*336o&pa2b662%6)&yto%-0(51&r!z(k
      - DEBUG=True
      - MONGODB_NAME=mongodb
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=rootpassword
      - MONGODB_DATABASE=youtube_watcher
      - FIELD_ENCRYPTION_KEY=_-1Fw33Pl_6jSXK6NUxm02MnYjODOzrJjCFMPUuxOnY=
      - KAFKA_BOOTSTRAP_SERVERS=broker:29092
        
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-server:7.3.0
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:29092
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'

  control-center:
    image: confluentinc/cp-enterprise-control-center:7.3.0
    hostname: control-center
    container_name: control-center
    depends_on:
      - broker
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'broker:29092'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1

volumes:
  mongodb_data_container: