apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-watcher
  labels:
    app: youtube-watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      name: youtube-watcher
  template:
    metadata:
      labels:
        name: youtube-watcher
    spec:
      containers:
        - name: youtube-watcher
          image: "tokhna/youtube_watcher:${RELEASE_VERSION}"
          command:
            - "/bin/sh"
            - "/home/app/webapp/docker-entrypoint.sh"
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: youtube-watcher-secrets
                  key: SECRET_KEY
            - name: ALLOWED_HOSTS
              valueFrom:
                secretKeyRef:
                  name: youtube-watcher-secrets
                  key: ALLOWED_HOSTS
            - name: DEBUG
              valueFrom:
                secretKeyRef:
                  name: youtube-watcher-secrets
                  key: DEBUG
            - name: MONGODB_NAME
              valueFrom:
                secretKeyRef:
                  name: youtube-watcher-secrets
                  key: MONGODB_NAME
            - name: MONGODB_HOST
              valueFrom:
                secretKeyRef:
                  name: youtube-watcher-secrets
                  key: MONGODB_HOST
            - name: MONGODB_PORT
              valueFrom:
                secretKeyRef:
                  name: youtube-watcher-secrets
                  key: MONGODB_PORT
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: youtube-watcher-secrets
                  key: MONGODB_USERNAME
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: youtube-watcher-secrets
                  key: MONGODB_PASSWORD
            - name: MONGODB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: youtube-watcher-secrets
                  key: MONGODB_DATABASE
            - name: FIELD_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: youtube-watcher-secrets
                  key: FIELD_ENCRYPTION_KEY
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                secretKeyRef:
                  name: youtube-watcher-secrets
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: ACS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: youtube-watcher-secrets
                  key: ACS_CONNECTION_STRING
            - name: ACS_SENDER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: youtube-watcher-secrets
                  key: ACS_SENDER_EMAIL
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-watcher-consumer
  labels:
    app: youtube_watchyoutube_watcher_consumerer
spec:
  replicas: 1
  selector:
    matchLabels:
      name: youtube-watcher-consumer
  template:
    metadata:
      labels:
        name: youtube-watcher-consumer
    spec:
      containers:
        - name: youtube-watcher-consumer
          image: "tokhna/youtube_watcher:${RELEASE_VERSION}"
          command:
            - "faust"
            - "-A"
            - "youtube_watcher.consumer:app"
            - "worker"
            - "-l"
            - "info"
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: youtube-watcher-secrets
                  key: SECRET_KEY
            - name: DEBUG
              valueFrom:
                secretKeyRef:
                  name: youtube-watcher-secrets
                  key: DEBUG
            - name: ALLOWED_HOSTS
              valueFrom:
                secretKeyRef:
                  name: youtube-watcher-secrets
                  key: ALLOWED_HOSTS
            - name: MONGODB_NAME
              valueFrom:
                secretKeyRef:
                  name: youtube-watcher-secrets
                  key: MONGODB_NAME
            - name: MONGODB_HOST
              valueFrom:
                secretKeyRef:
                  name: youtube-watcher-secrets
                  key: MONGODB_HOST
            - name: MONGODB_PORT
              valueFrom:
                secretKeyRef:
                  name: youtube-watcher-secrets
                  key: MONGODB_PORT
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: youtube-watcher-secrets
                  key: MONGODB_USERNAME
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: youtube-watcher-secrets
                  key: MONGODB_PASSWORD
            - name: MONGODB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: youtube-watcher-secrets
                  key: MONGODB_DATABASE
            - name: FIELD_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: youtube-watcher-secrets
                  key: FIELD_ENCRYPTION_KEY
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                secretKeyRef:
                  name: youtube-watcher-secrets
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: ACS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: youtube-watcher-secrets
                  key: ACS_CONNECTION_STRING
            - name: ACS_SENDER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: youtube-watcher-secrets
                  key: ACS_SENDER_EMAIL
---
# START Service
apiVersion: v1
kind: Service
metadata:
  name: youtube-watcher
  labels:
    app: youtube-watcher
spec:
  type: LoadBalancer
  ports:
    - port: 80 #port that the service exposes
      targetPort: 8000 #port that the app is receiving requests from via the pod
  selector:
    name: youtube-watcher
# END SERVICE
