# Generated by Django 4.1.5 on 2023-02-08 05:57

from django.db import migrations
import django_choices_field.fields
import receivers.models


class Migration(migrations.Migration):
    dependencies = [
        ("receivers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receiver",
            name="type",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("email", "Email"),
                    ("slack", "Slack"),
                    ("discord", "Discord"),
                    ("telegram", "Telegram"),
                ],
                choices_enum=receivers.models.Receiver.Type,
                max_length=8,
            ),
        ),
    ]
