# Generated by Django 4.1.5 on 2023-02-03 05:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playlists", "0009_remove_video_dislikes"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="playlist",
            constraint=models.UniqueConstraint(
                fields=("owner", "playlist_id"), name="owner_playlist_id"
            ),
        ),
    ]
