# Generated by Django 4.1.5 on 2023-02-01 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("channels", "0003_channel_video_delete_channels"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile_channels",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
