# Generated by Django 4.1.5 on 2023-02-03 03:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("channels", "0004_channel_owner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="channel",
            old_name="is_active",
            new_name="isActive",
        ),
        migrations.RenameField(
            model_name="video",
            old_name="is_active",
            new_name="isActive",
        ),
        migrations.RemoveField(
            model_name="channel",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="channel",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="video",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="video",
            name="updated_at",
        ),
    ]
