# Generated by Django 4.1.5 on 2023-02-03 04:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("channels", "0005_rename_is_active_channel_isactive_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="comments",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="channel",
            name="likes",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="channel",
            name="subscribers",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="channel",
            name="views",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="video",
            name="comments",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="video",
            name="dislikes",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="video",
            name="likes",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="video",
            name="views",
            field=models.IntegerField(null=True),
        ),
    ]
