# Generated by Django 4.1.5 on 2023-02-03 04:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "channels",
            "0008_alter_channel_comments_alter_channel_likes_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="dislikes",
        ),
    ]
