# Generated by Django 4.1.5 on 2023-02-07 03:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("channels", "0010_channel_owner_channel_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="thumbnail",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddConstraint(
            model_name="video",
            constraint=models.UniqueConstraint(
                fields=("video_id", "channel_id"), name="video_id_channel_id"
            ),
        ),
    ]
